name: NPM publish

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Install
              run: yarn install
            # set up git since we will later push to the repo
            - run: git config --global user.name "GitHub CD bot"
            - run: git config --global user.email "dmitrii@moralis.io"
            # upgrade npm version in package.json to the tag used in the release.
            - run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
            # build the project
            - run: npm run build
            # run tests just in case
            - run: npm test
            - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

            - name: publish to NPM as latest version
              if: '!github.event.release.prerelease'
              run: npm publish --tag latest
              env:
                  # Use a token to publish to NPM. See below for how to set it up
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: publish to NPM beta version
              if: 'github.event.release.prerelease'
              run: npm publish --tag beta
              env:
                  # Use a token to publish to NPM. See below for how to set it up
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            # push the version changes to GitHub
            - run: git push origin HEAD:master
              env:
                  # The secret is passed automatically. Nothing to configure.
                  github-token: ${{ secrets.GITHUB_TOKEN }}
